version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '8001:5432'
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - backend

  bot:
    build: ./bot
    image: alexcingolani/rti:rti_bot
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db


  api:
    build: ./api
    image: alexcingolani/rti:rti_api
    depends_on:
      - db
    ports:
      - 8080:8083
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres-data:
  
networks:
  backend:
    driver: bridge
    name: backend