version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '8001:5432'
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - backend

  rti_bot:
    build: ./bot
    env_file:
      - .env
    # environment:
    #   - DB_URL=postgresql+pg8000://alexander:alexander@db:5432/alexander
    networks:
      - backend
    depends_on:
      - db


  rti_api:
    build: ./api
    depends_on:
      - db
    ports:
      - 8080:8083

    env_file:
      - .env
    environment:
      - DB_URL=postgresql+pg8000://alexander:alexander@db:5432/alexander
    networks:
      - backend

volumes:
  postgres-data:
  
networks:
  backend:
    driver: bridge
    name: backend